//created on: Apr 29, 2017
package droolscours

//list any import classes here.



//declare any global variables here

import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import util.OutputDisplay;

global OutputDisplay showResult;


rule "Your First Rule revisted agian"

    when
        Account( )
    then
        showResult.showText("The account exists");
end

rule "Credit rule"
	when
         $cash :CashFlow( $accno : accountNo , type == CashFlow.CREDIT )
         $acc : Account( accountno ==$accno )
	then
	   $acc.setBalance($acc.getBalance() + $cash.getAmount());
	   showResult.showText("Account no " + $acc.getAccountno() + " has now a balance of " + $acc.getBalance() );
end