//created on: Apr 18, 2017
package droolscours

//list any import classes here.

import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import util.OutputDisplay;
import java.math.BigDecimal;
import java.util.List;
//declare any global variables here
global OutputDisplay showResult;
global List list;

rule "Account Exists"

    when
        Account( )
    then
        showResult.showText("This Account exits");

end

rule "Rule of Accounting Periond that are inserting"
    //include attributes such as "salience" here...
    when
    	AccountingPeriod( )
        
    then
        showResult.showText("This AccountingPeriod exits");
end

rule "Rule of CashFlow that are inserting"
    //include attributes such as "salience" here...
    when
    	CashFlow( )
        
    then
        showResult.showText("This CashFlow exits");
        AccountingPeriod newPeriod = new AccountingPeriod();
        insert (newPeriod);
end

rule "rule1"
	dialect "java"
	when
		$bd : BigDecimal( )
		eval ( $bd.compareTo( BigDecimal.ZERO ) > 0 )
	then
		list.add( $bd );
end
